apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  labels:
    env: dev
    dc: IN
spec:
  containers:
  - name: "mycon1"
    image: "httpd"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    dc: IN
    env: dev
  name: mypod1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    dc: IN
    env: dev
  type: NodePort


